### PR TITLE
Fixes additional merge error

### PR DESCRIPTION
**Pull request by alx-xo**

### CODE REVIEW

**Review by barnwell — APPROVED** [review]

**Comment by ggamel** [comment]
@AnalogMemory @barnwell Thanks, both. 👏

**Comment by jcklpe** [comment]
@ggamel Hey would you say this is the most active fork of the wp-sync-db/wp-sync-db fork? I'm having trouble find an up to date or maintained version of this plugin. I used this tool and this seems to be one of the top: http://www.toddsifleet.com/projects/github-forks#wp-sync-db/wp-sync-db

**Comment by ggamel** [comment]
@thedonquixotic Hi, sorry for the late reply. I'm not sure if this is the most active fork. If it is, I'm happy to merge any PRs submitted and help wherever.

**Comment by jcklpe** [comment]
@ggamel  No worries! I ended up trying a couple and found this one worked: https://github.com/corysimmons/wp-sync-db

**Pull request merged**
